apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-excercise-deployment
  labels:
    app: docker-excercise
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-excercise
  template:
    metadata:
      labels:
        app: docker-excercise
    spec:
      containers:
      - name: docker-excercise
        image: sample-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
      terminationGracePeriodSeconds: 60