apiVersion: v1
kind: Service
metadata:
  name: docker-sample-service
  namespace: test
spec:
  selector:
    app: docker-excercise
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080